# Generated by Django 5.1.3 on 2025-04-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='rol',
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='email',
            field=models.EmailField(blank=True, default=1, max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
