# Generated by Django 5.1.3 on 2025-04-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_usuariopersonalizado_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='apellidos',
            field=models.CharField(default='Sin apellido', max_length=100),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('empleado', 'Empleado')], default='Sin nombre', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
