# Generated by Django 5.1.3 on 2025-04-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuariopersonalizado_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='rol',
            field=models.CharField(blank=True, choices=[('cliente', 'Cliente'), ('empleado', 'Empleado')], max_length=10, null=True),
        ),
    ]
