# Generated by Django 5.1.3 on 2025-04-25 01:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cupon', '0003_cupon_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('litros_vendidos', models.IntegerField()),
                ('total_venta', models.IntegerField()),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('credito', 'Credito')], max_length=10)),
                ('fecha_compra', models.DateField(default=datetime.date.today)),
                ('cupon', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioCupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=False, null=True)),
                ('cupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cupon.cupon')),
            ],
        ),
    ]
